name: Ansible User Creation
on:
  push:
    branches: [ main ]
jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ansible
      run: |
        sudo apt update
        sudo apt install ansible -y
    - name: Copy SSH Key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        USER1_PUBLIC_KEY: ${{ secrets.USER1_PUBLIC_KEY }}
        USER2_PUBLIC_KEY: ${{ secrets.USER2_PUBLIC_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "$USER1_PUBLIC_KEY" > user1.pub
        echo "$USER2_PUBLIC_KEY" > user2.pub
    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i inventory.ini create_users.yml --extra-vars "ansible_ssh_common_args='-o StrictHostKeyChecking=no'"
